---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: javawebapp
  template:
    metadata:
      labels:
        name: javawebapp
    spec:
      containers:
      - name: nginx
        image: ravikumara0004/app5:0.0.3
        ports:
        - containerPort: 8080


